daqI:
  device: Dev1
  channels:
    - Dev1/ai0
    - Dev1/ai1
  freq: 10000
  averages: 10
  omissions: 100  # number of sample intervals to skip between reads
  terminal: RSE
daqO:
  device: cDAQ1Mod1
  channels:
    - cDAQ1Mod1/ao0
    - cDAQ1Mod1/ao1
  low: 0.0
  high: 3.0
  interval: 0.5
  seed: 1234
  waveform_cycles_hz: 1.0   # <-- independent AO waveform frequency (cycles per second)
